### ISSUE TITLE
Dependencies issue using transit-java with Android

### ISSUE THREAD

**Issue by yume117** [cognitect/transit-java#11]
I got Transit-java from MavenCentral using gradle  compile 'com.cognitect:transit-java:0.8.269'

Upon build I get this Warning : 
```
Warning:Dependency org.json:json:20090211 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage with jarjar to change the class packages
```
It slow down the build quite a bit. Could something be done knowing that android already got some dependencies ?

**Comment by puredanger** [comment]
As has been mentioned on the transit mailing list, it would be possible to remove this (unnecessary) transitive dependency by switching to just including jackson-core instead of jackson-datatype-json-org.

Before:

```
[INFO] com.cognitect:transit-java:jar:dev
[INFO] +- junit:junit:jar:3.8.1:test
[INFO] +- com.fasterxml.jackson.datatype:jackson-datatype-json-org:jar:2.3.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.3.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.3.2:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.3.0:compile
[INFO] |  \- org.json:json:jar:20090211:compile
[INFO] +- org.msgpack:msgpack:jar:0.6.10:compile
[INFO] |  +- com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[INFO] |  \- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] \- commons-codec:commons-codec:jar:1.10:compile
```

After:

```
[INFO] com.cognitect:transit-java:jar:dev
[INFO] +- junit:junit:jar:3.8.1:test
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.3.2:compile
[INFO] +- org.msgpack:msgpack:jar:0.6.10:compile
[INFO] |  +- com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[INFO] |  \- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] \- commons-codec:commons-codec:jar:1.10:compile
```

As far as I can tell, this builds and all tests pass and it reduces unnecessary deps. But I could be missing something important.

**Comment by puredanger** [comment]
May also want to consider bumping to a newer version of jackson-core (latest stable atm is 2.6.3).

**Comment by puredanger** [comment]
I have changed the dependency (but not updated the version). The offending dependency should no longer be a transitive dependency of transit-java as of version 0.8.311.
