### ISSUE TITLE
MsgpackEmitter encodes byte[] as a base64 string

### ISSUE THREAD

**Issue by chris-zen** [cognitect/transit-java#17]
When writing an array of bytes Transit uses the `BinaryWriteHandler` which gives the `b` tag. Then for that tag, the `AbstractEmitter` calls the function `emitBinary`. Its implementation in `MsgpackEmitter` encodes the array of bytes as Base64 and emits an string as follows:
```java
byte[] encodedBytes = Base64.encodeBase64((byte[])b);
emitString(Constants.ESC_STR, "b", new String(encodedBytes), asMapKey, cache);
```
Reading the specs of MessagePack I see that they have [native support for encoding binary data](https://github.com/msgpack/msgpack/blob/master/spec.md#formats-bin) without having to use strings encoded as Base64. I can understand this strategy for the JSON emitters but not for the Msgpack one.

**Comment by chris-zen** [comment]
I just realised that the Transit specs mandate to encode binary data as a base64 string. I don't really understand this decision, and makes me realise that using the MSGPACK format is not that much better than using the JSON one.

**Comment by puredanger** [comment]
FYI, there is more discussion of this here: https://github.com/cognitect/transit-format/issues/2
