### ISSUE TITLE
Bump com.fasterxml.jackson.core/jackson-core

### ISSUE THREAD

**Issue by plexus** [cognitect/transit-java#25]
Would it be possible to update this dependency? The version used is 2.3.2, while the latest is 2.8.6.

This impacts transit-clj, which now clashes with the version used in Cheshire.

Thanks!

**Comment by puredanger** [comment]
Should probably be fine to upgrade but will need to do some review of the change log and testing.

https://github.com/FasterXML/jackson-core/blob/master/release-notes/VERSION

**Comment by puredanger** [comment]
Updated and project tests pass 1b3bcac2ecb74efdfe25fd298a670f8a9a655ecc

**Comment by puredanger** [comment]
Released in transit-java 0.8.324 and transit-clj 0.8.300

**Comment by plexus** [comment]
Awesome! Thanks for the quick turnaround.

![cake](https://cloud.githubusercontent.com/assets/32212/23861792/6c4d478a-080b-11e7-977a-ede7481ceeba.gif)
